/**
 * FILE: server/scripts/seedControlGroup.js
 * PURPOSE: Generate synthetic illustrative ControlGroupRecord rows for the
 *          impact estimation methodology demonstration.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * PLACEHOLDER DATA — ILLUSTRATIVE ONLY
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * ALL rows generated by this script are SYNTHETIC.  They are produced by a
 * deterministic seeded pseudo-random function and do NOT represent real people
 * who did not undergo vocational training.  No survey, census, or administrative
 * dataset was used as a source.
 *
 * The employment distribution chosen below (≈ 48% placed, i.e. EMPLOYED +
 * SELF_EMPLOYED) is ILLUSTRATIVE.  It is set a few points below the assumed
 * 45–55% baseline range to leave visible headroom for the "uplift" demonstration.
 * This figure is NOT sourced from any real study, NSSO/PLFS round, or official
 * report.  It was chosen solely to make the methodology demonstrable.
 *
 * To use real comparison data:
 *   1. Import records from a real non-trainee population (e.g. PLFS/NSSO micro-data
 *      filtered to the same age/district/qualification strata).
 *   2. Set isSynthetic = false on those rows.
 *   3. No changes to impactMeasurementService.js are required — computeImpact()
 *      reads ControlGroupRecord regardless of isSynthetic value.
 *
 * Usage:
 *   node server/scripts/seedControlGroup.js          # default 200 rows
 *   node server/scripts/seedControlGroup.js 500      # custom count
 *   npm run db:seed-control                          # via npm script
 *
 * The script will NOT overwrite existing rows by default.  Pass --force to
 * delete all existing ControlGroupRecord rows before re-seeding.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * DEPENDENCIES: server/lib/prisma.js, server/services/impactMeasurementService.js
 * (imports getAgeBand — the single canonical bucketing function — to guarantee
 *  that stored ageBand values always match what computeImpact() produces from
 *  Trainee.dateOfBirth.  Change the bucket boundaries only in the service file.)
 */

import { PrismaClient } from '@prisma/client'
import { getAgeBand } from '../services/impactMeasurementService.js'

// Module-level PrismaClient used when the script runs as CLI.
// When imported by analytics.js, the shared singleton is passed as an arg.
const _cliPrisma = new PrismaClient()

// ── Seeded PRNG (mulberry32) ───────────────────────────────────────────────────
// A well-known, simple 32-bit PRNG that accepts a numeric seed.
// Using this instead of Math.random() guarantees byte-for-byte identical output
// on every run with the same seed — essential for reproducible demos.
// Reference: https://gist.github.com/tommyettinger/46a874533244883189143505d203312c
function mulberry32(seed) {
  return function () {
    seed |= 0
    seed = (seed + 0x6d2b79f5) | 0
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

// Fixed seed — changing this would change all generated rows.
// Kept constant so re-runs are reproducible during judging / demos.
const FIXED_SEED = 0xdeadbeef
const rand = mulberry32(FIXED_SEED)

function randItem(arr) {
  return arr[Math.floor(rand() * arr.length)]
}

// ── Domain distributions ───────────────────────────────────────────────────────
// Districts and qualifications mirror the real trainee population so that
// strata overlap and the comparison is meaningful for more trainees.

const DISTRICTS = [
  'Pune', 'Mumbai', 'Nagpur', 'Nashik', 'Aurangabad',
  'Bengaluru', 'Mysuru', 'Hyderabad', 'Chennai', 'Coimbatore',
  'Delhi', 'Gurugram', 'Noida', 'Jaipur', 'Udaipur',
  'Kolkata', 'Howrah', 'Bhopal', 'Indore', 'Raipur',
  'Satara', 'Ranchi', 'Patna', 'Lucknow', 'Kanpur',
]

const QUALIFICATIONS = ['Below 10th', '10th Pass', '12th Pass', 'Graduate']
// Weighted distribution (heavier on 10th and 12th, lighter on graduate)
const QUAL_WEIGHTS = [0.15, 0.35, 0.35, 0.15]

const AGE_BANDS = ['18-25', '26-35', '36-45', '46+']
// Weighted distribution matching typical vocational training demographics
const AGE_WEIGHTS = [0.45, 0.35, 0.15, 0.05]

// Employment status distribution for the SYNTHETIC control group.
// Target: ≈ 48% placed (EMPLOYED + SELF_EMPLOYED), intentionally illustrative.
// These weights are NOT sourced from any real study.
const STATUS_WEIGHTS = [
  { status: 'EMPLOYED',      weight: 0.35 },
  { status: 'SELF_EMPLOYED', weight: 0.13 },
  { status: 'SEARCHING',     weight: 0.28 },
  { status: 'IN_TRAINING',   weight: 0.14 },
  { status: 'OTHER',         weight: 0.10 },
]

// Wage bands, only applicable for EMPLOYED/SELF_EMPLOYED
const WAGE_BANDS = ['0-10k', '10-20k', '20k+']
const WAGE_WEIGHTS = [0.45, 0.40, 0.15]

function weightedChoice(items) {
  // items: array of { status, weight } or reuse for generic weighted picks
  const r = rand()
  let cumulative = 0
  for (const item of items) {
    cumulative += item.weight
    if (r < cumulative) return item.status || item
  }
  return items[items.length - 1].status || items[items.length - 1]
}

function weightedPick(values, weights) {
  const r = rand()
  let cumulative = 0
  for (let i = 0; i < values.length; i++) {
    cumulative += weights[i]
    if (r < cumulative) return values[i]
  }
  return values[values.length - 1]
}

// ── Main seeder function ────────────────────────────────────────────────────────
export async function seedControlGroup(count = 200, prisma = _cliPrisma) {
  const records = []

  for (let i = 0; i < count; i++) {
    const ageBand = weightedPick(AGE_BANDS, AGE_WEIGHTS)
    const district = randItem(DISTRICTS)
    const priorQualification = weightedPick(QUALIFICATIONS, QUAL_WEIGHTS)
    const employmentStatus = weightedChoice(STATUS_WEIGHTS)

    let wageBand = null
    if (employmentStatus === 'EMPLOYED' || employmentStatus === 'SELF_EMPLOYED') {
      wageBand = weightedPick(WAGE_BANDS, WAGE_WEIGHTS)
    }

    records.push({
      ageBand,
      district,
      priorQualification,
      employmentStatus,
      wageBand,
      isSynthetic: true,
    })
  }

  await prisma.controlGroupRecord.createMany({ data: records })
  return records.length
}

// ── CLI entry point ────────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2)
  const force = args.includes('--force')
  const countArg = args.find((a) => /^\d+$/.test(a))
  const count = countArg ? parseInt(countArg, 10) : 200

  if (count < 1 || count > 100000) {
    console.error('Error: count must be between 1 and 100,000')
    process.exit(1)
  }

  const existing = await _cliPrisma.controlGroupRecord.count()
  if (existing > 0 && !force) {
    console.error(
      `\n⚠  ControlGroupRecord already has ${existing} rows.\n` +
      '   Pass --force to delete all existing rows and re-seed.\n' +
      '   Example: node server/scripts/seedControlGroup.js 200 --force\n'
    )
    await _cliPrisma.$disconnect()
    process.exit(1)
  }

  if (existing > 0 && force) {
    await _cliPrisma.controlGroupRecord.deleteMany()
    console.log(`Deleted ${existing} existing ControlGroupRecord rows.`)
  }

  console.log(
    `\nGenerating ${count} SYNTHETIC illustrative ControlGroupRecord rows...`
  )
  console.log('NOTE: This data is placeholder — see script header for limitations.\n')

  const seeded = await seedControlGroup(count, _cliPrisma)

  console.log(`✅  Done — seeded ${seeded} rows.`)

  await _cliPrisma.$disconnect()
}

// Only run main() when this file is the direct entry point (CLI).
// When imported as a module (by analytics.js), only the exports run.
const isDirectRun = process.argv[1] &&
  new URL(import.meta.url).pathname.replace(/\\/g, '/').endsWith(
    process.argv[1].replace(/\\/g, '/').split('/').pop()
  )

if (isDirectRun) {
  main().catch((err) => {
    console.error('Seed script failed:', err)
    process.exit(1)
  })
}
